activities/urls.py
from django.urls import path
from activities import views

app_name='activities'

urlpatterns = [
    path('projects', views.projects, name="projects"),
    path('projects/<str:slug>', views.project, name="project"),
    path('site-visits', views.visits, name="visits"),
    path('site-visits/<str:slug>', views.visit, name="visit"),
]

administration/urls.py
from django.urls import path
from administration import views

app_name='administration'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login', views.loginView, name="login"),
    path('logout', views.logoutView, name="logout"),
    path('bats', views.batList, name="bat-list"),
    path('bats/create', views.batCreate, name="bat-create"),
    path('bats/<int:id>', views.batUpdateDelete, name="bat-update-delete"),
    path('projects', views.projectList, name="project-list"),
    path('projects/create', views.projectCreate, name="project-create"),
    path('projects/<int:id>', views.projectUpdateDelete, name="project-update-delete"),
    path('visits', views.visitList, name="visit-list"),
    path('visits/create', views.visitCreate, name="visit-create"),
    path('visits/<int:id>', views.visitUpdateDelete, name="visit-update-delete"),
    path('authors', views.authorListCreate, name="author-list-create"),
    path('authors/<int:id>', views.authorUpdateDelete, name="author-update-delete"),
    path('articles', views.articleListCreate, name="article-list-create"),
    path('articles/<int:id>', views.articleUpdateDelete, name="article-update-delete"),
]

base/urls.py
from django.urls import path
from base import views

app_name='base'

urlpatterns = [
    path('', views.index, name="index"),
    path('articles', views.articles, name="articles"),
    path('search', views.search, name="search"),
]

bats/urls.py
from django.urls import path
from bats import views

app_name='bats'

urlpatterns = [
    path('', views.index, name="index"),
    path('gallery', views.gallery, name="gallery"),
    path('<str:slug>', views.detail, name="detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('django-admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include("base.urls")),
    path('admin/', include("administration.urls")),
    path('bats/', include("bats.urls")),
    path('activities/', include("activities.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^languages/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bats/models.py
from django.db import models
from administration import models as administration_models
from django import urls
from core import helpers
from django.conf import settings

class Family(models.Model):
    name = administration_models.NameField(unique=True)
    slug = administration_models.SlugField()

    class Meta:
        verbose_name_plural = "Families"

    def __str__(self):
        return self.name


class Genus(models.Model):
    name = administration_models.NameField(unique=True)
    slug = administration_models.SlugField()
    family = models.ForeignKey(Family, related_name="family", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Genus"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = helpers.generateSlug(self.name)
        return super().save(*args, **kwargs)


class Species(models.Model):
    name = administration_models.NameField(unique=True)
    slug = administration_models.SlugField()
    cover_image = administration_models.ImageField()
    genus = models.ForeignKey(Genus, related_name="genus", on_delete=models.CASCADE)
    is_red_book = models.BooleanField(default=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Species"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return urls.reverse("bats:detail", kwargs={"slug": self.slug})
    
    @property
    def get_absolute_cover_image_url(self):
        return "{0}{1}".format(settings.MEDIA_URL, self.cover_image.url)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = helpers.generateSlug(self.name)
        return super().save(*args, **kwargs)


class SpeciesAttributes(models.Model):
    species = models.ForeignKey(Species, related_name="species_attributes", on_delete=models.CASCADE)
    description = administration_models.RichTextEditorField()
    habitat = administration_models.RichTextEditorField()
    threats = administration_models.RichTextEditorField()
    distribution = administration_models.RichTextEditorField()
    conservation = administration_models.RichTextEditorField()
    biology = administration_models.RichTextEditorField()
    language = administration_models.LanguageField()

    def __str__(self):
        return str(self.species)


class SpeciesImage(models.Model):
    species = models.ForeignKey(Species, on_delete=models.CASCADE, related_name="species_images")
    image = administration_models.ImageField()

    def __str__(self):
        return str(self.species)
    

class SpeciesRedBook(models.Model):
    language = administration_models.LanguageField()
    species = models.ForeignKey(Species, related_name="species_red_book", on_delete=models.CASCADE)
    description = administration_models.RichTextEditorField()

    def __str__(self):
        return str(self.species)    

bats/views.py
from django.shortcuts import render
from bats import models
from django.core import paginator
from django.db.models import Prefetch
from django.utils import translation
from django.views.decorators import http


@http.require_GET
def index(request):
    genusSlug = request.GET.get("genus", None)

    if genusSlug:
        bats = models.Species.objects.filter(genus__slug=genusSlug)
    else:
        bats = models.Species.objects.all()

    pagination = paginator.Paginator(bats, 10)
    pageNumber = request.GET.get('page')
    bats = pagination.get_page(pageNumber)

    genus = models.Genus.objects.all()
    return render(request, "bats/index.html", {"bats": bats, "genus": genus})


@http.require_GET
def gallery(request):
    bats = models.Species.objects.select_related("genus").all()
    return render(request, "bats/gallery.html", {"bats": bats})


@http.require_GET
def detail(request, slug: str):
    bat_attributes = models.SpeciesAttributes.objects.filter(
        language=translation.get_language())
    bat_red_book = models.SpeciesRedBook.objects.filter(
        language=translation.get_language())

    prefetch_species_attributes = Prefetch(
        'species_attributes', queryset=bat_attributes)
    prefetch_bat_red_book = Prefetch('species_red_book', queryset=bat_red_book)

    bat = models.Species.objects.select_related("genus").prefetch_related(
        'species_images', prefetch_species_attributes, prefetch_bat_red_book).get(slug=slug)

    bat.species_attributes_result = bat.species_attributes.all().first()
    bat.species_red_book_result = bat.species_red_book.all().first()
    return render(request, "bats/detail.html", {"bat": bat})

templates/components/article.html
{% load i18n %}
{% load static %}

<div class="col-lg-12">
  <div class="pricing-item pricing-item--style-2">
    <div class="row align-items-center">
      <div class="col-lg-9">
        <h6 class="pricing-item__plan">{{article.name}} - {{article.author}}</h6>
      </div>
      <div class="col-lg-3 col-xl-2 text-lg-right">
        <a
          class="pricing-item__button button button--main"
          target="_blank"
          href="{{article.url}}"
          >{% translate "Visit" %}</a
        >
      </div>
    </div>
  </div>
</div>

templates/components/author.html
<div class="row">
  <div class="col-lg-4 col-md-6 col-12 d-lg-block">
    <div class="testimonials__img">
      <img class="img--bg" src="{{author.cover_image.url}}" alt="img" />
    </div>
  </div>
  <div class="col-lg-8 col-md-6 col-12">
    <div class="row align-items-center">
      <div class="col-md-7">
        <div class="heading heading--primary">
          <h2 class="heading__title">
            <span>{{author.author_attributes_result.name}}</span>
          </h2>
        </div>
      </div>
      <div class="col-md-5">
        <div
          class="testimonials--style-1__dots dots--style-2 text-md-right"
        ></div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="testimonials-slider testimonials-slider--style-1">
          <div class="testimonials-slider__item">
            <div class="testimonials-slider__text">
              {{author.author_attributes_result.description|safe}}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/bat.html
{% load i18n %}

<div class="animal-block"><img class="img--bg" src="{{bat.cover_image.url}}"/>
    <div class="animal-block__details">
        <h6 class="animal-block__title">{{bat.name}}</h6><a class="animal-block__link" href="{% url 'bats:detail' slug=bat.slug %}">{% translate "More" %}</a>
    </div>
</div>

templates/components/bat2.html
{% load i18n %}

<div class="animal-block"><img class="img--bg" src="{{bat.cover_image.url}}"/>
  <div class="animal-block__details">
      <h6 class="animal-block__title">{{bat.name}}</h6><a class="animal-block__link" href="{% url 'bats:detail' slug=bat.slug %}">{% translate "More" %}</a>
  </div>
</div>

templates/components/footer.html
{% load static %}
{% load i18n %}

<footer class="footer footer--front-3">
  <div class="container">
    <div class="row bottom-50">
      <div class="col-md-6 col-lg-4">
        <a class="logo logo--footer" href="index.html"
          ><img
            class="logo__img"
            src="{% static 'img/logo.png' %}"
            alt="logo"
        /></a>
        <div class="footer__details">
          <p>
            <strong>{% translate "Phone" %}:</strong>
            <a href="tel:{{config_vars.phone}}">{{config_vars.phone}}</a>
          </p>
          <p>
            <strong>{% translate "Email" %}:</strong>
            <a href="mailto:{{config_vars.email}}">{{config_vars.email}}</a>
          </p>
        </div>
        <ul class="socials bottom-30">
          <li class="socials__item">
            <a class="socials__link" href="#"
              ><i class="fa fa-facebook" aria-hidden="true"></i
            ></a>
          </li>
          <li class="socials__item">
            <a class="socials__link" href="#"
              ><i class="fa fa-youtube-play" aria-hidden="true"></i
            ></a>
          </li>
          <li class="socials__item">
            <a class="socials__link" href="#"
              ><i class="fa fa-instagram" aria-hidden="true"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="col-lg-5 d-none d-lg-block">
        <h6 class="footer__title">{% translate "Menu" %}</h6>
        <ul class="footer-menu footer-menu--style-2">
          <li class="footer-menu__item">
            <a class="footer-menu__link" href="{% url 'base:index' %}">{% translate "Home" %}</a>
          </li>
          <li class="footer-menu__item">
            <a class="footer-menu__link" href="{% url 'bats:index' %}">{% translate "Bats" %}</a>
          </li>
          <li class="footer-menu__item">
            <a class="footer-menu__link" href="{% url 'activities:projects' %}">{% translate "Projects" %}</a>
          </li>
          <li class="footer-menu__item">
            <a class="footer-menu__link" href="{% url 'activities:visits' %}">{% translate "Site Visits" %}</a>
          </li>
          <li class="footer-menu__item">
            <a class="footer-menu__link" href="{% url 'base:articles' %}">{% translate "Articles" %}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/components/gallery.html
<section class="section gallery no-padding-top no-padding-bottom">
  <div class="row gallery-masonry no-gutters">
      {% for image in images %}
      <div class="category_1 col-sm-6 col-lg-4 col-xl-3 gallery-masonry__item">
          <a class="gallery-masonry__img gallery-masonry__item--height-1" href="{{image.image.url}}" data-fancybox="gallery">
              <img class="img--bg" src="{{image.image.url}}" alt="img"/>
          </a>
      </div>
      {% endfor %}
  </div>
</section>

templates/components/header.html
{% load static %}
{% load i18n %}
{% load query_transform %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages%}

<header class="header shop-header header-f3">
  <div class="header__lower">
    <div class="row">
      <div class="col-12 d-flex align-items-center justify-content-between">
        <div class="header__lower-inner">
          <ul class="lang-select">
            <li class="lang-select__item lang-select__item--active">
              <span>{{LANGUAGE_CODE|upper}}</span>
              <ul class="lang-select__sub-list">
                {% for lang in languages %}
                <li><a href="/{{ lang.code }}{{ request.get_full_path|slice:'3:' }}">
                  {{lang.code|upper}}
                </a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <div class="header__phones d-none d-xl-block">
            {% translate "Phone" %}: <a href="tel:{{config_vars.phone}}">{{config_vars.phone}}</a>
          </div>
        </div>
        <div class="header__lower-inner d-none d-xl-block">
          <ul class="header__socials">
            <li>
              <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            </li>
            <li>
              <a href="#"
                ><i class="fa fa-youtube-play" aria-hidden="true"></i
              ></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="header__top">
    <div class="row align-items-center">
      <div class="col-6 col-lg-3">
        <a class="logo" href="{% url 'base:index' %}"
          ><img
            class="logo__img"
            src="{% static 'img/logo.png' %}"
            alt="logo"
        /></a>
      </div>
      <div class="col-6 col-lg-9 d-flex justify-content-end align-items-center">
        <ul class="main-menu">
          <li class="main-menu__item {% if 'base' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.home.route %}main-menu__item--active{% endif %}">
            <a class="main-menu__link" href="{% url menu.home.route %}"><span>{{menu.home.text}}</span></a>
          </li>
          <li class="main-menu__item {% if 'bats' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.bats.route %}main-menu__item--active{% endif %}">
            <a class="main-menu__link" href="{% url menu.bats.route %}"><span>{{menu.bats.text}}</span></a>
          </li>
          <li class="main-menu__item {% if 'bats' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.gallery.route %}main-menu__item--active{% endif %}">
            <a class="main-menu__link" href="{% url menu.gallery.route %}"><span>{{menu.gallery.text}}</span></a>
          </li>
          <li class="main-menu__item main-menu__item--has-child {% if 'activities' in request.resolver_match.namespaces %}main-menu__item--active{% endif %}">
            <a class="main-menu__link" href="javascript:void(0);"
              ><span>{% translate "Activities" %}</span></a
            >
            <ul class="main-menu__sub-list sub-list--style-2">
                {% for item in menu.activities %}
                <li class="{% if 'activities' in request.resolver_match.namespaces and request.resolver_match.url_name in item.route %}item--active{% endif %}">
                  <a href="{% url item.route %}"><span>{{item.text}}</span></a>
                </li>
                {% endfor %}
            </ul>
          </li>
          <li class="main-menu__item {% if 'base' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.articles.route %}main-menu__item--active{% endif %}"><a class="main-menu__link" href="{% url menu.articles.route %}"><span>{{menu.articles.text}}</span></a></li>

          {% if user.is_authenticated %}
          <li class="main-menu__item main-menu__item--has-child {% if 'administration' in request.resolver_match.namespaces %}main-menu__item--active{% endif %}">
            <a class="main-menu__link" href="javascript:void(0);"
              ><span>{% translate "Admin" %}</span></a
            >
            <ul class="main-menu__sub-list sub-list--style-2">
                {% for item in menu.admin %}
                <li class="{% if 'administration' in request.resolver_match.namespaces and request.resolver_match.url_name in item.route %}item--active{% endif %}">
                  <a href="{% url item.route %}"><span>{{item.text}}</span></a>
                </li>
                {% endfor %}
            </ul>
          </li>
          <li class="main-menu__item main-menu__item--has-child">
            <a class="main-menu__link" href="javascript:void(0);"
              ><span>{{user.username}}</span></a
            >
            <ul class="main-menu__sub-list sub-list--style-2">
              <li>
                <form action="{% url 'administration:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="button btn-danger">{% translate "Logout" %}</button>
                </form>
              </li>
            </ul>
          </li>
          {% endif %}
          <form class="search-form" action="{% url 'base:search' %}">
            <input class="search-form__input" type="search" name="search" placeholder="{% translate "Search" %}"/>
            <button class="search-form__submit" type="submit">
              <svg class="icon">
                <use xlink:href="#search"></use>
              </svg>
            </button>
          </form>
        </ul>
          
        <div class="hamburger">
          <div class="hamburger-box">
            <div class="hamburger-inner"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

templates/components/menu.html
{% load i18n %}
{% load query_transform %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages%}

<div class="menu-dropdown menu-dropdown--front-3">
  <div class="menu-dropdown__inner" data-value="start">
    <div class="screen screen--start">
      <div class="screen__item {% if 'base' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.home.route %}item--active{% endif %}">
        <a class="screen__link" href="{% url menu.home.route %}">{{menu.home.text}}</a>
      </div>
      <div class="screen__item {% if 'bats' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.bats.route %}item--active{% endif %}"><a class="screen__link" href="{% url menu.bats.route %}">{{menu.bats.text}}</a></div>
      {% if user.is_authenticated %}
      <div class="screen__item screen--trigger {% if 'administration' in request.resolver_match.namespaces %}item--active{% endif %}" data-category="admin">
        <span>{% translate "Admin" %}</span
        ><span>
          <svg class="icon">
            <use xlink:href="#chevron"></use></svg
        ></span>
      </div>
      {% endif %}
      <div class="screen__item {% if 'bats' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.gallery.route %}item--active{% endif %}">
        <a class="screen__link" href="{% url menu.gallery.route %}">{{menu.gallery.text}}</a>
      </div>
      <div class="screen__item {% if 'base' in request.resolver_match.namespaces and request.resolver_match.url_name in menu.articles.route %}item--active{% endif %}"><a class="screen__link" href="{% url menu.articles.route %}">{{menu.articles.text}}</a></div>
      <div class="screen__item screen--trigger {% if 'activities' in request.resolver_match.namespaces %}item--active{% endif %}" data-category="activities">
        <span>{% translate "Activities" %}</span
        ><span>
          <svg class="icon">
            <use xlink:href="#chevron"></use></svg
        ></span>
      </div>
      <div class="screen__item screen--trigger" data-category="language">
        <span>{% translate "Language" %}</span
        ><span>
          <svg class="icon">
            <use xlink:href="#chevron"></use></svg
        ></span>
      </div>

      <div class="screen__item">
        <form class="search-form" action="{% url 'base:search' %}">
          <input class="search-form__input" type="search" name="search" placeholder="{% translate "Search" %}"/>
          <button class="search-form__submit" type="submit">
            <svg class="icon">
              <use xlink:href="#search"></use>
            </svg>
          </button>
        </form>
      </div>
      
      <ul class="screen__socials">
        <li>
          <a class="item--facebook" href="#"
            ><i class="fa fa-facebook" aria-hidden="true"></i
          ></a>
        </li>
        <li>
          <a class="item--youtube" href="#"
            ><i class="fa fa-youtube-play" aria-hidden="true"></i
          ></a>
        </li>
        <li>
          <a class="item--instagram" href="#"
            ><i class="fa fa-instagram" aria-hidden="true"></i
          ></a>
        </li>
      </ul>
      
    </div>
  </div>
  {% if user.is_authenticated %}
  <div class="menu-dropdown__inner" data-value="admin">
    <div class="screen screen--sub">
      <div class="screen__heading">
        <h6 class="screen__back">
          <svg class="icon">
            <use xlink:href="#chevron-left"></use>
          </svg>
          <span>{% translate "Admin" %}</span>
        </h6>
      </div>
      {% for item in menu.admin %}
      <div class="screen__item {% if 'administration' in request.resolver_match.namespaces and request.resolver_match.url_name in item.route %}item--active{% endif %}">
        <a class="screen__link" href="{% url item.route %}">{{item.text}}</a>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
  <div class="menu-dropdown__inner" data-value="activities">
    <div class="screen screen--sub">
      <div class="screen__heading">
        <h6 class="screen__back">
          <svg class="icon">
            <use xlink:href="#chevron-left"></use>
          </svg>
          <span>{% translate "Activities" %}</span>
        </h6>
      </div>
      {% for item in menu.activities %}
      <div class="screen__item {% if 'activities' in request.resolver_match.namespaces and request.resolver_match.url_name in item.route %}item--active{% endif %}">
        <a class="screen__link" href="{% url item.route %}">{{item.text}}</a>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="menu-dropdown__inner" data-value="language">
    <div class="screen screen--sub">
      <div class="screen__heading">
        <h6 class="screen__back">
          <svg class="icon">
            <use xlink:href="#chevron-left"></use>
          </svg>
          <span>{% translate "Language" %}</span>
        </h6>
      </div>
      {% for lang in languages %}
      <div class="screen__item">
        <a class="screen__link" href="/{{ lang.code }}{{ request.get_full_path|slice:'3:' }}">{{lang.code|upper}}</a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

templates/components/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
    {% if message.tags %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% else %}
        <div class="alert alert-info alert-dismissible" role="alert" >
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
</div>
{% endfor %}

templates/components/project.html
<div class="blog-item">
    <div class="blog-item__img"><img class="img--bg" src="{{project.cover_image.url}}" alt="blog"/>
        <div class="blog-item__date"><span>02</span><span>Nov</span></div>
    </div>
    <h4 class="blog-item__title"><a href="{% url 'activities:project' slug=project.slug %}">{{project.name}}</a></h4>
    <p class="text-dark">{{project.description|truncatechars:255|safe}}</p>
</div>

templates/components/promo copy.html
{% load i18n %}
{% load static %}
<section class="promo-primary">
  <picture>
    <source
      srcset="{{promo_image}}"
      media="(min-width: 992px)"
    />
    <img class="img--bg" src="{{promo_image}}" alt="img" />
  </picture>
  <div class="container">
    <div class="row">
      <div class="col-auto">
        <div class="align-container">
          <div class="align-container__item">
            <span class="promo-primary__pre-title"
              >{% translate promo_pre_title %}</span
            >
            <h1 class="promo-primary__title">
              <span>{% translate promo_title %}</span>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/components/promo.html
{% load i18n %}
{% load static %}
<section class="promo-primary">
  <picture>
    <source
      srcset="{% static promo_image %}"
      media="(min-width: 992px)"
    />
    <img class="img--bg" src="{% static promo_image %}" alt="img" />
  </picture>
  <div class="container">
    <div class="row">
      <div class="col-auto">
        <div class="align-container">
          <div class="align-container__item">
            <span class="promo-primary__pre-title"
              >{% translate promo_pre_title %}</span
            >
            <h1 class="promo-primary__title">
              <span>{% translate promo_title %}</span>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/components/statistics.html
{% load i18n %}
{% load static %}

<section class="section about-terrarium no-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-5 col-xl-7 px-5 py-2">
        <div class="heading heading--style-2 heading--green">
          <h2 class="heading__title">
            <span>{% translate "Our country" %}</span>
          </h2>
        </div>
        <p class="bottom-40"><strong>{{statistics.country_statistics}}</strong></p>
        <div class="row offset-30">
          <div class="col-sm-4">
            <div class="counter-item counter-item--front">
              <div class="counter-item__top">
                <h6 class="counter-item__title">{% translate "Bats" %}</h6>
              </div>
              <div class="counter-item__lower">
                <span class="js-counter color--green">{{statistics.bat_count}}</span>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="counter-item counter-item--front">
              <div class="counter-item__top">
                <h6 class="counter-item__title">{% translate "Projects" %}</h6>
              </div>
              <div class="counter-item__lower">
                <span class="js-counter color--green">{{statistics.project_count}}</span>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="counter-item counter-item--front">
              <div class="counter-item__top">
                <h6 class="counter-item__title">{% translate "Site Visits" %}</h6>
              </div>
              <div class="counter-item__lower">
                <span class="js-counter color--green">{{statistics.visit_count}}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-7 col-xl-5">
        <img
          class="w-100"
          src="{% static 'img/map.jpg' %}"
          alt="img"
        />
      </div>
    </div>
  </div>
</section>

templates/components/visit.html
<div class="events-item">
    <div class="events-item__img">
        <div class="events-item__date"><span>11</span><span>Nov</span></div><img class="img--bg" src="{{visit.cover_image.url}}"/>
    </div>
    <h6 class="events-item__title"><a class="events-item__link" href="{% url 'activities:visit' slug=visit.slug %}">{{visit.name}}</a></h6>
    <p class="text-dark">{{visit.description|truncatechars:255|safe}}</p>
</div>