administration/urls.py
from django.urls import path
from administration import views

app_name='administration'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login', views.loginView, name="login"),
    path('logout', views.logoutView, name="logout"),
    path('bats', views.batList, name="bat-list"),
    path('bats/create', views.batCreate, name="bat-create"),
    path('bats/<int:id>', views.batUpdateDelete, name="bat-update-delete"),
    path('projects', views.projectList, name="project-list"),
    path('projects/create', views.projectCreate, name="project-create"),
    path('projects/<int:id>', views.projectUpdateDelete, name="project-update-delete"),
    path('visits', views.visitList, name="visit-list"),
    path('visits/create', views.visitCreate, name="visit-create"),
    path('visits/<int:id>', views.visitUpdateDelete, name="visit-update-delete"),
    path('authors', views.authorListCreate, name="author-list-create"),
    path('authors/<int:id>', views.authorUpdateDelete, name="author-update-delete"),
    path('articles', views.articleListCreate, name="article-list-create"),
    path('articles/<int:id>', views.articleUpdateDelete, name="article-update-delete"),
]

base/urls.py
from django.urls import path
from base import views

app_name='base'

urlpatterns = [
    path('', views.index, name="index"),
    path('articles', views.articles, name="articles"),
    path('search', views.search, name="search"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('django-admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include("base.urls")),
    path('admin/', include("administration.urls")),
    path('bats/', include("bats.urls")),
    path('activities/', include("activities.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^languages/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from ckeditor_uploader import fields as ckeditorFields
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from core import helpers


class RichTextEditorField(ckeditorFields.RichTextUploadingField):
    description = _("Rich text editor field")

    def __init__(self, *args, **kwargs):
        kwargs['null'] = True
        kwargs['blank'] = True
        super().__init__(*args, **kwargs)


class LanguageField(models.CharField):
    description = _("Language field")
    
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 2
        kwargs['choices'] = settings.LANGUAGES
        kwargs['default'] = settings.LANGUAGE_CODE
        super().__init__(*args, **kwargs)


class ImageField(models.ImageField):
    description = _("Image field")

    def __init__(self, *args, **kwargs):
        kwargs['upload_to'] = helpers.uploadImageLocation
        super().__init__(*args, **kwargs)


class SlugField(models.SlugField):
    description = _("Slug field")

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 255
        kwargs['null'] = True
        kwargs['blank'] = True
        kwargs['unique'] = True
        super().__init__(*args, **kwargs)


class NameField(models.CharField):
    description = _("Name field")

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 200
        kwargs['null'] = False
        kwargs['blank'] = False
        super().__init__(*args, **kwargs)

administration/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from bats import models as batModels
from activities import models as activityModels
from base import models as baseModels
from django.views.decorators import http
from django.contrib.auth import decorators as authDecorators, logout, authenticate, login
from administration import forms
from django.db.models import Prefetch
from django.contrib import messages
from django.utils import translation
from django.utils.translation import gettext as _


@http.require_http_methods(["GET", "POST"])
def loginView(request):
    if request.POST:
        form = forms.LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data['password']
            try:
                user = authenticate(
                    request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect(request.GET.get('next'))
                raise Exception(
                    f'{_("Username")} {_("or")} {_("Password!")} {_("is incorrect!")}')
            except Exception as err:
                return render(request, "administration/auth/login.html", {"form": form, "login_err": str(err)})
        return render(request, "administration/auth/login.html", {"form": form})
    else:
        form = forms.LoginForm()
        return render(request, "administration/auth/login.html", {"form": form})


@authDecorators.login_required
@http.require_POST
def logoutView(request):
    logout(request)
    return redirect("base:index")


@authDecorators.login_required
@http.require_GET
def dashboard(request):
    return render(request, "administration/dashboard.html")


@authDecorators.login_required
@http.require_GET
def batList(request):
    bats = batModels.Species.objects.select_related("genus")
    return render(request, "administration/bats/list.html", {"bats": bats})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST"])
def batCreate(request):
    if request.POST:
        form = forms.BatSpeciesCreateForm(request.POST, request.FILES)
        attributes_formset = forms.SpeciesAttributesFormset(
            data=request.POST, files=request.FILES)
        red_book_formset = forms.SpeciesRedBookFormset(
            data=request.POST, files=request.FILES)
        images_formset = forms.SpeciesImageFormset(
            data=request.POST, files=request.FILES)
        if form.is_valid() and attributes_formset.is_valid() and images_formset.is_valid() and red_book_formset.is_valid():
            bat = form.save()
            attributes = attributes_formset.save(commit=False)
            images = images_formset.save(commit=False)
            red_book = red_book_formset.save(commit=False)
            for attr in attributes:
                attr.species = bat
                attr.save()
            for img in images:
                img.species = bat
                img.save()
            for item in red_book:
                item.species = bat
                item.save()
            messages.success(request, f'{_("Bat")}  {_("added!")}')
            return redirect("administration:bat-list")
        messages.error(request, f'{_("Bat")}  {_("cannot be added!")}')
        return render(request, "administration/bats/create.html", {"form": form, "attributes_formset": attributes_formset, "images_formset": images_formset, "red_book_formset": red_book_formset})
    form = forms.BatSpeciesCreateForm()
    attributes_formset = forms.SpeciesAttributesFormset()
    images_formset = forms.SpeciesImageFormset()
    red_book_formset = forms.SpeciesRedBookFormset()
    return render(request, "administration/bats/create.html", {"form": form, "attributes_formset": attributes_formset, "images_formset": images_formset, "red_book_formset": red_book_formset})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST", "DELETE"])
def batUpdateDelete(request, id):
    if request.method == "DELETE":
        batModels.Species.objects.get(id=id).delete()
        return HttpResponse(f'{_("Bat")}  {_("deleted!")}')

    bat = batModels.Species.objects.prefetch_related(
        'species_images').get(id=id)
    if request.POST:
        form = forms.BatSpeciesUpdateForm(
            instance=bat, data=request.POST, files=request.FILES)
        attributes_formset = forms.SpeciesAttributesFormset(
            instance=bat, data=request.POST, files=request.FILES)
        images_formset = forms.SpeciesImageFormset(
            instance=bat, data=request.POST, files=request.FILES)
        red_book_formset = forms.SpeciesRedBookFormset(
            data=request.POST, files=request.FILES)
        if form.is_valid() and attributes_formset.is_valid() and images_formset.is_valid() and red_book_formset.is_valid():
            bat = form.save()
            attributes_formset.save()
            images_formset.save()
            red_book_formset.save()
            messages.success(request, f'{_("Bat")}  {_("updated!")}')
            return redirect("administration:bat-update-delete", id=id)
        messages.error(request, f'{_("Bat")}  {_("cannot be added!")}')
        return render(request, "administration/bats/update.html", {"form": form, "bat": bat, "attributes_formset": attributes_formset, "images_formset": images_formset, "red_book_formset": red_book_formset})
    form = forms.BatSpeciesUpdateForm(instance=bat)
    attributes_formset = forms.SpeciesAttributesFormset(instance=bat)
    images_formset = forms.SpeciesImageFormset(instance=bat)
    red_book_formset = forms.SpeciesRedBookFormset(instance=bat)
    return render(request, "administration/bats/update.html", {"form": form, "bat": bat, "attributes_formset": attributes_formset, "images_formset": images_formset, "red_book_formset": red_book_formset})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST"])
def authorListCreate(request):
    if request.POST:
        form = forms.AuthorForm(data=request.POST, files=request.FILES)
        attributes_formset = forms.AuthorAttributesFormset(
            data=request.POST, files=request.FILES)
        if form.is_valid() and attributes_formset.is_valid():
            author = form.save()
            attributes = attributes_formset.save(commit=False)
            for attr in attributes:
                attr.author = author
                attr.save()
            messages.success(request, f'{_("Author")}  {_("added!")}')
            return redirect("administration:author-list-create")
        messages.error(request, f"{_('Author')} {_('cannot be added!')}")
        return render(request, "administration/authors/list.html", {"form": form, "attributes_formset": attributes_formset})
    form = forms.AuthorForm()
    attributes_formset = forms.AuthorAttributesFormset()
    authors = baseModels.Author.objects.prefetch_related(
        'author_attributes').all()
    return render(request, "administration/authors/list.html", {"form": form, "authors": authors, "attributes_formset": attributes_formset})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST", "DELETE"])
def authorUpdateDelete(request, id):
    if request.method == "DELETE":
        baseModels.Author.objects.get(id=id).delete()
        return HttpResponse(f'{_("Author")}  {_("deleted!")}')

    author_attributes = baseModels.AuthorAttributes.objects.filter(
        language=translation.get_language())
    prefetch = Prefetch('author_attributes', queryset=author_attributes)
    author = baseModels.Author.objects.prefetch_related(prefetch).get(id=id)
    author.author_attributes_result = author.author_attributes.all().first()
    if request.POST:
        form = forms.AuthorForm(
            instance=author, data=request.POST, files=request.FILES)
        attributes_formset = forms.AuthorAttributesFormset(
            data=request.POST, files=request.FILES)
        if form.is_valid() and attributes_formset.is_valid():
            author = form.save()
            attributes_formset.save()
            messages.success(request, f'{_("Author")}  {_("updated!")}')
            return redirect("administration:author-update-delete", id=id)
        messages.error(request, f"{_('Author')} {_('cannot be updated!')}")
        return render(request, "administration/authors/update.html", {"form": form, "author": author, "attributes_formset": attributes_formset})
    form = forms.AuthorForm(instance=author)
    attributes_formset = forms.AuthorAttributesFormset(instance=author)
    return render(request, "administration/authors/update.html", {"form": form, "author": author, "attributes_formset": attributes_formset})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST"])
def articleListCreate(request):
    if request.POST:
        form = forms.ArticleForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'{_("Article")}  {_("added!")}')
            return redirect("administration:article-list-create")
        messages.error(request, f"{_('Article')} {_('cannot be added!')}")
        return render(request, "administration/articles/list.html", {"form": form})
    form = forms.ArticleForm()
    articles = baseModels.Article.objects.all()
    return render(request, "administration/articles/list.html", {"form": form, "articles": articles})


@authDecorators.login_required
@http.require_http_methods(["GET", "POST", "DELETE"])
def articleUpdateDelete(request, id):
    if request.method == "DELETE":
        baseModels.Article.objects.get(id=id).delete()
        return HttpResponse(f'{_("Article")}  {_("deleted!")}')

    article = get_object_or_404(baseModels.Article, id=id)
    if request.POST:
        form = forms.ArticleForm(
            instance=article, data=request.POST, files=request.FILES)
        if form.is_valid():

administration/templates/administration/visits/create.html
{% extends "app.html" %} {% load i18n %} {% load static %} 
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
{% endblock stylesheet %} {% block title %}{% translate "Admin" %} - {% translate "Add Site Visit" %}{% endblock title %} 
{% block content %}
<section class="section">
  <div class="container py-5">
    <div class="bottom-40">
      <ul class="breadcrumbs breadcrumbs--with-dot">
        <li class="breadcrumbs__item">
          <a
            class="breadcrumbs__link"
            href="{% url 'administration:dashboard' %}"
            >{% translate "Dashboard" %}</a
          >
        </li>
        <li class="breadcrumbs__item">
          <a
            class="breadcrumbs__link"
            href="{% url 'administration:visit-list' %}"
            >{% translate "Site Visits" %}</a
          >
        </li>
        <li class="breadcrumbs__item breadcrumbs__item--active">
          {% translate "Add site visit" %}
        </li>
      </ul>
    </div>
    <div class="row bottom-50">
      <div class="col-12 bottom-20">
        <div class="heading heading--primary heading--center">
          <h2 class="heading__title no-margin-bottom">
            <span>{% translate "Add site visit" %}</span>
          </h2>
        </div>
      </div>
    </div>
    <div class="container my-3">
      {% include 'components/messages.html' with messages=messages %}
    </div>
    <div class="row">
      <div class="col-12">
        <form class="form" method="post" enctype="multipart/form-data">
          {{ form.media }}
          <div class="card card-body bottom-40">
            {% include "components/form/hidden_fields.html" with hidden_fields=form.hidden_fields %}
            {{form.non_form_errors}}
            <div class="row">
              <div class="col-12 bottom-20">
                <label class="form-label" for="{{ form.name.id_for_label }}"
                  >{{ form.name.label }}</label
                >
                {{form.name}} {{ form.name.errors }}
              </div>
              <div class="col-12 bottom-20">
                <label
                  class="form-label"
                  for="{{ form.cover_image.id_for_label }}"
                  >{{ form.cover_image.label }}</label
                >
                {{form.cover_image}} {{ form.cover_image.errors }}
              </div>
            </div>
          </div>

          <div class="card bottom-40">
            <div class="card-header">
              <h4>{% translate "Site Visit" %} {% translate "data for different languages" %}</h4>
            </div>
            <div class="card-body">
              {{ attributes_formset.management_form }} 
              {% for formset_item in attributes_formset %} 
              {% include "components/form/hidden_fields.html" with hidden_fields=formset_item.hidden_fields %}
              {{formset_item.non_form_errors}}
              <div class="row">
                <h4>{% translate "Data" %} {{forloop.counter}}</h4>
                {{ formset_item.media }}
                <div class="col-12 col-md-6 col-xl-4 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.language.id_for_label }}"
                    >{{ formset_item.language.label }}</label
                  >
                  {{formset_item.language}} {{ formset_item.language.errors }}
                </div>
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.description.id_for_label }}"
                    >{{ formset_item.description.label }}</label
                  >
                  {{formset_item.description}} {{ formset_item.description.errors }}
                </div>
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.results.id_for_label }}"
                    >{{ formset_item.results.label }}</label
                  >
                  {{formset_item.results}} {{ formset_item.results.errors }}
                </div>
              </div>
              <hr />
              {% endfor %}
            </div>
          </div>

          <div class="card bottom-40">
            <div class="card-header">
              <h5>{% translate "Additional images" %}</h5>
            </div>
            <div class="card-body">
              {{ images_formset.management_form }} 
              {% for formset_item in images_formset %} 
              {% include "components/form/hidden_fields.html" with hidden_fields=formset_item.hidden_fields %}
              {{formset_item.non_form_errors}} 
              {{ formset_item.media }}
              <h6>{% translate "Image" %} {{forloop.counter}}</h6>
              <div class="row">
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.image.id_for_label }}"
                    >{{ formset_item.image.label }}</label
                  >
                  {{formset_item.image}} {{ formset_item.image.errors }}
                </div>
              </div>
              <hr />
              {% endfor %}
            </div>
          </div>
          <div class="bottom-20 text-center">
            <button class="form__submit text_decoration-none" type="submit">
              {% translate "Save" %}
            </button>
          </div>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

administration/templates/administration/visits/list.html
{% extends 'app.html' %} {% load static %} {% load i18n %} 
{% block title %}{% translate "Admin" %} - {% translate "Site Visits" %}{% endblock title %} 
{%  block stylesheet %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
{% endblock stylesheet %} 
{% block content %}
<section class="section elements">
  <div class="container py-5">
    <div class="bottom-40">
      <ul class="breadcrumbs breadcrumbs--with-dot">
        <li class="breadcrumbs__item">
          <a
            class="breadcrumbs__link"
            href="{% url 'administration:dashboard' %}"
            >{% translate "Dashboard" %}</a
          >
        </li>
        <li class="breadcrumbs__item breadcrumbs__item--active">
          {% translate "Site Visits" %}
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="col-xl-10">
        <h4 class="elements__title">{% translate "Site Visits" %}</h4>
        <a
          class="button button--main button--rounded"
          href="{% url 'administration:visit-create'%}"
          >{% translate "Add Site Visit" %}</a
        >
      </div>
    </div>
    <div class="container my-3">
      {% include 'components/messages.html' with messages=messages %}
    </div>
    <div class="card card-body my-3">
      <div class="table-responsive">
        <table class="table align-middle table-striped table-hover">
          <thead class="table-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">{% translate "Name" %}</th>
              <th scope="col">{% translate "Operations" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for visit in visits %}
            <tr class="data-row">
              <td>{{visit.id}}</td>
              <td>{{visit.name}}</td>
              <td>
                <a
                  class="btn btn-warning"
                  href="{% url 'administration:visit-update-delete' id=visit.id %}"
                  >{% translate "Edit" %}</a
                >
                <button
                  type="button"
                  class="btn btn-danger btn-delete"
                  data-url="{% url 'administration:visit-update-delete' id=visit.id %}"
                >
                  {% translate "Delete" %}
                </button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock content%} {% block scripts %}
<script>
  let csrftoken = "{{ csrf_token }}";
</script>
<script src="{% static 'js/delete-table-record.js' %}"></script>
{% endblock scripts %}

administration/templates/administration/visits/update.html
{% extends "app.html" %} {% load i18n %} {% load static %} 
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
{% endblock stylesheet %} {% block title %}{% translate "Admin" %} - {{visit.name}}{% endblock title %} 
{% block content %}
<section class="section">
  <div class="container py-5">
    <div class="bottom-40">
      <ul class="breadcrumbs breadcrumbs--with-dot">
        <li class="breadcrumbs__item">
          <a
            class="breadcrumbs__link"
            href="{% url 'administration:dashboard' %}"
            >{% translate "Dashboard" %}</a
          >
        </li>
        <li class="breadcrumbs__item">
          <a
            class="breadcrumbs__link"
            href="{% url 'administration:visit-list' %}"
            >{% translate "Site Visits" %}</a
          >
        </li>
        <li class="breadcrumbs__item breadcrumbs__item--active">
          {{visit.name}}
        </li>
      </ul>
    </div>
    <div class="row bottom-50">
      <div class="col-12 bottom-20">
        <div class="heading heading--primary heading--center">
          <h2 class="heading__title no-margin-bottom">
            <span>{% translate "Edit" %} - {{visit.name}}</span>
          </h2>
        </div>
      </div>
    </div>
    <div class="container my-3">
      {% include 'components/messages.html' with messages=messages %}
    </div>
    <div class="row">
      <div class="col-12">
        <form class="form" method="post" enctype="multipart/form-data">
          {{ form.media }}
          <div class="card card-body bottom-40">
            {% include "components/form/hidden_fields.html" with hidden_fields=form.hidden_fields %}
            {{form.non_form_errors}}
            <div class="row">
              <div class="col-12 bottom-20">
                <label class="form-label" for="{{ form.name.id_for_label }}"
                  >{{ form.name.label }}:</label
                >
                {{form.name}} {{ form.name.errors }}
              </div>
              <div class="col-12 col-md-6 col-xl-6 bottom-20">
                <label
                  class="form-label"
                  for="{{ form.cover_image.id_for_label }}"
                  >{{ form.cover_image.label }}</label>
                {{form.cover_image}} 
                {{ form.cover_image.errors }}
              </div>
              <div class="col-12 col-md-6 bottom-20">
                <img
                    src="{{form.cover_image.value.url}}"
                    class="my-2"
                    style="width: 100px; height: 100px"
                />
              </div>
            </div>
          </div>

          <div class="card bottom-40">
            <div class="card-header">
              <h4>{% translate "Site Visit" %} {% translate "data for different languages" %}</h4>
            </div>
            <div class="card-body">
              {{ attributes_formset.management_form }} 
              {% for formset_item in attributes_formset %}
              {% include "components/form/hidden_fields.html" with hidden_fields=formset_item.hidden_fields %}
              {{formset_item.non_form_errors}} 
              {{ formset_item.media }}
              <h4>{% translate "Data" %} {{forloop.counter}}</h4>
              <div class="row">
                <div class="col-12 button-20">
                  <div class="form-check">
                    <label
                      class="form-check-label text-danger"
                      for="{{ formset_item.DELETE.id_for_label }}"
                      >{{ formset_item.DELETE.label }}
                    </label>
                    <input
                      class="form-check-input"
                      type="checkbox"
                      name="{{ formset_item.DELETE.html_name }}"
                      id="{{ formset_item.DELETE.id_for_label }}"
                    />
                    {{ formset_item.DELETE.errors }}
                  </div>
                </div>
                <div class="col-12 col-md-6 col-xl-4 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.language.id_for_label }}"
                    >{{ formset_item.language.label }}:</label
                  >
                  {{formset_item.language}} {{ formset_item.language.errors }}
                </div>
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.description.id_for_label }}"
                    >{{ formset_item.description.label }}:</label
                  >
                  {{formset_item.description}} {{ formset_item.description.errors }}
                </div>
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.results.id_for_label }}"
                    >{{ formset_item.results.label }}:</label
                  >
                  {{formset_item.results}} {{ formset_item.results.errors }}
                </div>
              </div>
              <hr />
              {% endfor %}
            </div>
          </div>

          <div class="card bottom-40">
            <div class="card-header">
              <h5>{% translate "Additional images" %}</h5>
            </div>
            <div class="card-body">
              {{ images_formset.management_form }} 
              {% for formset_item in images_formset %} 
              {% include "components/form/hidden_fields.html" with hidden_fields=formset_item.hidden_fields %}
              {{formset_item.non_form_errors}} {{ formset_item.media }}
              <h6>{% translate "Image" %} {{forloop.counter}}</h6>
              <div class="row">
                <div class="col-12 bottom-20">
                  <div class="form-check">
                    <label
                      class="form-check-label text-danger"
                      for="{{ formset_item.DELETE.id_for_label }}"
                      >{{ formset_item.DELETE.label }}
                    </label>
                    <input
                      class="form-check-input"
                      type="checkbox"
                      name="{{ formset_item.DELETE.html_name }}"
                      id="{{ formset_item.DELETE.id_for_label }}"
                    />
                    {{ formset_item.DELETE.errors }}
                  </div>
                </div>
                <div class="col-12 bottom-20">
                  <label
                    class="form-label"
                    for="{{ formset_item.image.id_for_label }}"
                    >{{ formset_item.image.label }}:</label
                  >
                  {{formset_item.image}} {{ formset_item.image.errors }}
                </div>
              </div>
              <hr />
              {% endfor %}
            </div>
          </div>
          <div class="bottom-20 text-center">
            <button class="form__submit text_decoration-none" type="submit">
              {% translate "Save" %}
            </button>
          </div>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}